# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yzX8GXywoXjPbDt8LQFS22lhdFVnNAk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px



df = pd.read_csv("Anime.csv")
df

import pandas as pd

df = pd.read_csv("Anime.csv")

df.head()

df.info()

df.columns

# Duplicate rows remove
df.drop_duplicates(inplace=True)

# Missing values check
print(df.isnull().sum())

# Rating aur Episodes ko numeric banana
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
df["Episodes"] = pd.to_numeric(df["Episodes"], errors="coerce")

# Missing values remove
df = df.dropna(subset=["Rating", "Episodes"])

print("Dataset Shape :", df.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.bar(top10["Name"], top10["Rating"])

plt.xticks(rotation=70)

plt.xlabel("Anime")

plt.ylabel("Rating")

plt.title("Top 10 Highest Rated Anime")

plt.tight_layout()

plt.show()

import plotly.express as px

fig = px.bar(
    top10,
    x="Name",
    y="Rating",
    color="Rating",
    title="Top 10 Highest Rated Anime"
)

fig.show()

df.head()

df["Tags"].head(10)

